version: 1.0.16.{build}

os: Visual Studio 2017

environment:
  matrix:
    - platform: Win32
      configuration: Debug
    - platform: Win32
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

matrix:
  fast_finish: false

init:
  msbuild /version

build:
  parallel: true
  project: libsodium.vcxproj
  verbosity: minimal

artifacts:
  - path: **\libsodium.lib
    name: libsodium static library
    
  - path: **\libsodium.dll
    name: libsodium dynamic library

  - path: bin
    name: libsodium binaries
    
